const sleepMembers=['한끼방패','필사마','고마워디자이너','뽀글아줌마','오기글빛','오늘도맑음','마틸다의꿈','선경지명','레하놋','박윤정'];
const sleepAvatars=['🛡️','✍️','🎨','🫧','✨','🌤️','🌸','🧭','🌿','🌼'];
const demoSleep=[
{name:'한끼방패',today:6.4,avg:6.3,bed:'22:42',wake:'05:07',stable:82,note:'어제보다 조금 더 길게 쉬었어요. 오늘은 무리하지 않는 리듬이 좋아 보여요.'},
{name:'필사마',today:7.1,avg:6.8,bed:'22:18',wake:'05:24',stable:91,note:'이번 주 취침 시간이 꽤 안정적이에요. 회복 리듬이 차분하게 자리잡는 중.'},
{name:'고마워디자이너',today:6.8,avg:6.5,bed:'22:55',wake:'05:43',stable:79,note:'수면시간이 주간 평균보다 조금 늘었어요. 오늘은 좋은 흐름을 이어가는 날.'},
{name:'뽀글아줌마',today:5.9,avg:6.2,bed:'23:31',wake:'05:25',stable:64,note:'조금 짧게 잔 날이에요. 오늘은 일찍 쉬는 선택 하나가 더 중요해요.'},
{name:'오기글빛',today:6.6,avg:6.4,bed:'22:47',wake:'05:21',stable:84,note:'큰 변화 없이 꾸준한 흐름이에요. 이런 안정감이 오래 가는 힘이 됩니다.'},
{name:'오늘도맑음',today:7.3,avg:6.9,bed:'22:09',wake:'05:28',stable:93,note:'오늘은 회복이 좋은 편이에요. 잘 잔 날은 마음의 여유도 함께 체크해봐요.'},
{name:'마틸다의꿈',today:6.2,avg:6.4,bed:'23:04',wake:'05:16',stable:71,note:'조금 늦게 잠든 날이지만 전체 흐름은 유지되고 있어요.'},
{name:'선경지명',today:6.9,avg:6.7,bed:'22:36',wake:'05:31',stable:88,note:'주간 리듬이 안정적인 편이에요. 오늘도 같은 시간대에 쉬는 게 좋아요.'},
{name:'레하놋',today:6.1,avg:6.3,bed:'23:12',wake:'05:17',stable:69,note:'짧은 밤이 있었네요. 기록한 것만으로도 내 몸의 흐름을 알아가는 중이에요.'},
{name:'박윤정',today:7.0,avg:6.6,bed:'22:22',wake:'05:20',stable:90,note:'오늘은 충분히 회복한 편이에요. 좋은 밤의 감각을 기억해두면 좋아요.'}
];
function renderSleepDashboard(){const root=document.querySelector('#sleepDashboard');if(!root)return;const avg=(demoSleep.reduce((a,b)=>a+b.today,0)/demoSleep.length).toFixed(1);const seven=demoSleep.filter(x=>x.today>=7).length;const stable=Math.round(demoSleep.reduce((a,b)=>a+b.stable,0)/demoSleep.length);document.querySelector('#cohortAvg').textContent=avg+'h';document.querySelector('#sevenCount').textContent=seven+'명';document.querySelector('#rhythmAvg').textContent=stable+'%';const sky=document.querySelector('#sleepSky');const positions=[[12,22],[31,13],[52,25],[76,14],[88,34],[17,57],[39,48],[63,61],[83,70],[51,80]];sky.innerHTML=demoSleep.map((x,i)=>`<button class="sleep-star${i===0?' on':''}" data-sleep-index="${i}" style="left:${positions[i][0]}%;top:${positions[i][1]}%"><i style="width:${15+Math.max(0,x.today-5)*5}px;height:${15+Math.max(0,x.today-5)*5}px"></i><span>${x.name}</span></button>`).join('');document.querySelector('#sleepMemberCards').innerHTML=demoSleep.map((x,i)=>`<article class="sleep-person" data-card-index="${i}"><div class="sleep-person-top"><div class="avatar">${sleepAvatars[i]}</div><div><b>${x.name}</b><small>오늘의 회복 기록</small></div></div><div class="sleep-big">${x.today.toFixed(1)}<small> 시간</small></div><div class="sleep-meter"><i style="width:${Math.min(100,x.today/8*100)}%"></i></div><div class="sleep-meta"><div><small>취침</small><b>${x.bed}</b></div><div><small>기상</small><b>${x.wake}</b></div><div><small>주간 평균</small><b>${x.avg.toFixed(1)}h</b></div><div><small>리듬 안정도</small><b>${x.stable}%</b></div></div><span class="sleep-status${x.today<6.2?' warn':''}">${x.today>=7?'푹 쉬었어요 ✦':x.today>=6.3?'괜찮은 흐름':'오늘은 회복 우선'}</span></article>`).join('');document.querySelector('#rhythmRows').innerHTML=demoSleep.map(x=>`<div class="rhythm-row"><span>${x.name}</span><div class="rhythm-bar"><i style="width:${x.stable}%"></i></div><b>${x.stable}%</b></div>`).join('');bindSleepStars();showSleepMember(0)}
function showSleepMember(i){const x=demoSleep[i];document.querySelectorAll('.sleep-star').forEach((b,j)=>b.classList.toggle('on',j===i));document.querySelector('#sleepDetailAvatar').textContent=sleepAvatars[i];document.querySelector('#sleepDetailName').textContent=x.name;document.querySelector('#sleepDetailStatus').textContent=x.today>=7?'오늘은 회복이 좋은 밤이었어요':x.today>=6.3?'무난하게 회복한 밤이에요':'오늘은 몸을 조금 더 챙겨주세요';document.querySelector('#sdToday').textContent=x.today.toFixed(1)+'h';document.querySelector('#sdAvg').textContent=x.avg.toFixed(1)+'h';document.querySelector('#sdBed').textContent=x.bed;document.querySelector('#sdWake').textContent=x.wake;document.querySelector('#sleepRecoveryNote').textContent='“'+x.note+'”';}
function bindSleepStars(){document.querySelectorAll('.sleep-star').forEach(b=>b.addEventListener('click',()=>{showSleepMember(+b.dataset.sleepIndex);navigator.vibrate?.(12)}));}
document.addEventListener('DOMContentLoaded',renderSleepDashboard);