(()=>{
'use strict';
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
const members=['한끼방패','필사마','고마워디자이너','뽀글아줌마','오기글빛','오늘도맑음','마틸다의꿈','선경지명','레하놋','박윤정'];
const avatars=['🛡️','✍️','🎨','🫧','✨','🌤️','🌸','🧭','🌿','🌼'];
const memberMsgs=['함께 만들어가는 루틴의 힘을 보여주는 날이에요.','한 페이지의 꾸준함이 가족의 분위기를 바꿉니다.','일상을 예쁘게 바라보는 시선도 좋은 루틴입니다.','웃음 한 번이 지친 하루의 온도를 바꿀 수 있어요.','작은 빛을 계속 켜는 사람이 오늘의 주인공입니다.','맑은 마음으로 다시 시작하는 하루를 응원해요.','꿈을 잊지 않고 오늘을 살아내는 루틴을 응원합니다.','좋은 방향은 빠른 속도보다 오래 갑니다.','조용히 쌓인 시간이 결국 큰 힘이 됩니다.','오늘도 가족과 나를 함께 챙긴 하루를 응원해요.'];
const quotes=[['☾ 수면','잘 자는 것은 내일을 포기하는 일이 아니라, 내일을 지키는 일입니다.'],['⏱ 습관','대단한 하루보다 다시 돌아오는 하루가 습관을 만듭니다.'],['♡ 가족','가족에게 필요한 건 완벽한 사람이 아니라 다시 손 내미는 사람입니다.'],['🌱 성장','어제보다 조금 덜 지쳤다면 그것도 분명한 성장입니다.'],['☾ 수면','충분히 쉬는 부모는 가족에게 더 오래 따뜻할 수 있습니다.'],['⏱ 습관','꾸준함은 잘하는 날의 기록이 아니라 다시 시작한 날의 기록입니다.'],['♡ 가족','아이의 하루를 바꾸는 건 긴 조언보다 잠깐의 온전한 관심일 때가 많습니다.'],['🌱 성장','나를 돌보는 시간은 가족에게 돌아오는 시간입니다.']];
const spouse=['오늘 먼저 “고마워” 한마디 건네보기.','오늘은 해결책보다 “그랬구나”라고 먼저 말해보기.','“오늘 힘들지 않았어?”라고 먼저 물어보기.'];
const child=['오늘 하루 중 제일 웃겼던 일은 뭐였어?','오늘 누가 네 마음을 기분 좋게 해줬어?','지금 네가 가장 기대하고 있는 건 뭐야?'];
const missions=['배우자에게 고맙다고 한 번 말하기','아이에게 오늘 제일 좋았던 일 물어보기','오늘 평소보다 30분 일찍 눕기','가족 한 명과 눈을 보고 10초 웃기','오늘 내 몸에게 “수고했다” 말하기','아이 말을 끊지 않고 5분 들어주기','잠들기 전 휴대폰 20분 내려놓기','가족에게 먼저 사랑한다고 말하기'];
const sleep=[
{name:'한끼방패',today:6.4,avg:6.3,bed:'22:42',wake:'05:07',stable:82,note:'어제보다 조금 더 길게 쉬었어요. 오늘은 무리하지 않는 리듬이 좋아 보여요.'},
{name:'필사마',today:7.1,avg:6.8,bed:'22:18',wake:'05:24',stable:91,note:'이번 주 취침 시간이 꽤 안정적이에요. 회복 리듬이 차분하게 자리잡는 중.'},
{name:'고마워디자이너',today:6.8,avg:6.5,bed:'22:55',wake:'05:43',stable:79,note:'수면시간이 주간 평균보다 조금 늘었어요. 좋은 흐름을 이어가는 날.'},
{name:'뽀글아줌마',today:5.9,avg:6.2,bed:'23:31',wake:'05:25',stable:64,note:'조금 짧게 잔 날이에요. 오늘은 일찍 쉬는 선택 하나가 더 중요해요.'},
{name:'오기글빛',today:6.6,avg:6.4,bed:'22:47',wake:'05:21',stable:84,note:'큰 변화 없이 꾸준한 흐름이에요. 이런 안정감이 오래 가는 힘이 됩니다.'},
{name:'오늘도맑음',today:7.3,avg:6.9,bed:'22:09',wake:'05:28',stable:93,note:'오늘은 회복이 좋은 편이에요. 잘 잔 날은 마음의 여유도 함께 체크해봐요.'},
{name:'마틸다의꿈',today:6.2,avg:6.4,bed:'23:04',wake:'05:16',stable:71,note:'조금 늦게 잠든 날이지만 전체 흐름은 유지되고 있어요.'},
{name:'선경지명',today:6.9,avg:6.7,bed:'22:36',wake:'05:31',stable:88,note:'주간 리듬이 안정적인 편이에요. 오늘도 같은 시간대에 쉬는 게 좋아요.'},
{name:'레하놋',today:6.1,avg:6.3,bed:'23:12',wake:'05:17',stable:69,note:'짧은 밤이 있었네요. 기록한 것만으로도 내 몸의 흐름을 알아가는 중이에요.'},
{name:'박윤정',today:7.0,avg:6.6,bed:'22:22',wake:'05:20',stable:90,note:'오늘은 충분히 회복한 편이에요. 좋은 밤의 감각을 기억해두면 좋아요.'}
];
const dayKey=()=>{const d=new Date();return Math.floor(new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()/86400000)};
const slot=()=>{const h=new Date().getHours();return h>=5&&h<11?[0,'DAWN CARD','11:00']:h>=11&&h<17?[1,'DAY CARD','17:00']:h>=17&&h<23?[2,'EVENING CARD','23:00']:[3,'NIGHT CARD','05:00']};
function setText(sel,val){const e=q(sel);if(e)e.textContent=val}
function dailyCard(){const d=dayKey(),s=slot(),mix=(d*7+s[0]*3)%10;if(mix===2||mix===7)return['♡ 배우자에게 먼저 건넬 한마디',spouse[(d+s[0])%spouse.length]];if(mix===4||mix===9)return['🧒 오늘 아이에게 물어볼 질문',child[(d+s[0]*2)%child.length]];return quotes[(d*3+s[0])%quotes.length]}
function renderDaily(){const s=slot(),c=dailyCard(),i=(dayKey()*3+2)%members.length;setText('#quoteLabel',s[1]);setText('#quoteTheme',c[0]);setText('#quoteText','“'+c[1]+'”');setText('#nextQuote','다음 카드는 '+s[2]+'에 바뀝니다.');setText('#dailyMember',members[i]);setText('#dailyAvatar',avatars[i]);setText('#dailyMemberMsg',memberMsgs[i])}
function petState(){const n=+(localStorage.getItem('bumiMindCount')||0),stage=n>=30?4:n>=20?3:n>=12?2:n>=5?1:0;return{n,stage,char:['🌱','🌿','🌳','🌸','🌌'][stage],name:['마음씨앗','마음새싹','마음나무','마음꽃','별빛정원'][stage],next:[5,12,20,30,999][stage]}}
function renderPet(){const p=petState(),last=localStorage.getItem('bumiLastMood');setText('#petChar',p.char);setText('#petName',p.name);setText('#petDesc','마음을 돌본 기록 '+p.n+'회'+(p.next<999?' · 다음 성장까지 '+(p.next-p.n)+'회':' · 별빛정원 완성'));setText('#gardenChar',p.char);setText('#gardenCount',p.n+'회');setText('#gardenText',(last?'최근 마음은 “'+last+'”에 가까웠어요. ':'')+(p.next<999?'다음 성장까지 '+(p.next-p.n)+'번 남았어요.':'마음을 돌본 시간이 별빛정원으로 자랐어요.'))}
function renderHouse(){const count=846+(+(localStorage.getItem('bumiHouseStars')||0));setText('#routineCount',count+'개');const p=q('#houseProgress');if(p)p.style.width=Math.min(100,(count%1000)/10)+'%';setText('#houseText','다음 변화까지 '+(1000-(count%1000))+'개의 루틴이 남았어요.');const stage=q('#houseStage');if(stage)stage.className='house-stage s'+(count>=900?4:count>=700?3:count>=400?2:1);const stars=q('#stars');if(stars){stars.innerHTML='';for(let i=0;i<Math.min(14,Math.floor(count/70));i++){const e=document.createElement('span');e.textContent='✦';e.style.left=(8+(i*19)%86)+'%';e.style.top=(10+(i*27)%46)+'%';stars.appendChild(e)}}}
function renderMembers(){const root=q('#memberList');if(root)root.innerHTML=members.map((m,i)=>`<div class="member-mini"><div class="avatar">${avatars[i]}</div><div><b>${m}</b><small>부미챌 9기 멤버</small></div></div>`).join('')}
function renderMood(){const v=localStorage.getItem('bumiMood-'+dayKey());qa('.temp').forEach(b=>b.classList.toggle('on',v===b.dataset.temp));setText('#moodLabel',v?v+'° 기록됨':'미체크')}
function bindTabs(){qa('.nav button[data-tab]').forEach(b=>b.addEventListener('click',()=>{qa('.screen').forEach(s=>s.classList.toggle('on',s.id===b.dataset.tab));qa('.nav button').forEach(x=>x.classList.toggle('on',x===b));window.scrollTo(0,0);try{navigator.vibrate?.(12)}catch{}}))}
function bindCore(){const flip=q('#flipCard');if(flip)flip.addEventListener('click',()=>flip.classList.toggle('flipped'));
const mBtn=q('#missionBtn'),mDone=q('#missionDone'),key='bumiMission-'+dayKey();let reroll=+(localStorage.getItem(key+'-reroll')||0);const old=localStorage.getItem(key);if(old){setText('#missionResult','✨ '+old);if(mDone)mDone.style.display='block'}
if(mBtn)mBtn.addEventListener('click',()=>{const m=missions[(dayKey()+reroll*7)%missions.length];localStorage.setItem(key,m);reroll++;localStorage.setItem(key+'-reroll',reroll);setText('#missionResult','✨ '+m);if(mDone)mDone.style.display='block';mBtn.textContent=reroll>1?'오늘 미션 결정!':'한 번 더 뽑기';if(reroll>1)mBtn.disabled=true});
if(mDone)mDone.addEventListener('click',()=>{if(localStorage.getItem(key+'-done'))return;localStorage.setItem(key+'-done','1');localStorage.setItem('bumiHouseStars',+(localStorage.getItem('bumiHouseStars')||0)+1);mDone.textContent='오늘의 별 +1 ✦';mDone.disabled=true;renderHouse()});
qa('.temp').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('bumiMood-'+dayKey(),b.dataset.temp);localStorage.setItem('bumiLastMood',b.dataset.mood);renderMood()}));
const menu=q('#menuBtn'),drawer=q('#drawer'),shade=q('#shade');if(menu&&drawer)menu.addEventListener('click',()=>drawer.classList.add('on'));if(shade&&drawer)shade.addEventListener('click',()=>drawer.classList.remove('on'));qa('.menuitem[data-tab]').forEach(b=>b.addEventListener('click',()=>{q(`.nav button[data-tab="${b.dataset.tab}"]`)?.click();drawer?.classList.remove('on')}));
q('#heartBtn')?.addEventListener('click',()=>q('#counsel')?.classList.add('on'));q('#back')?.addEventListener('click',()=>q('#counsel')?.classList.remove('on'));
[['#targets .choice','#targets'],['#needs .choice','#needs'],['.cmood','.moods']].forEach(([sel,root])=>qa(sel).forEach(b=>b.addEventListener('click',()=>{qa(sel,q(root)||document).forEach(x=>x.classList.remove('on'));b.classList.add('on')})));
q('#solve')?.addEventListener('click',()=>{const w=q('#worry')?.value.trim();if(!w){alert('마음에 있는 이야기를 조금만 적어주세요.');return}const target=q('#targets .on')?.textContent||'관계',need=q('#needs .on')?.textContent||'위로',mood=q('.cmood.on')?.dataset.mood||'보통';setText('#a1','오늘 마음은 “'+mood+'”에 가까웠군요. '+target+'와의 관계를 중요하게 생각하기 때문에 더 크게 느껴졌을 수 있어요.');setText('#a2','누가 맞는지보다 서로 무엇을 지키고 싶었는지 먼저 살펴보면 좋겠어요.');setText('#a3',need.includes('해결책')?'오늘 모든 문제를 끝내려 하지 말고 서로의 생각을 10분씩 끊지 않고 들어보세요.':'오늘은 해결보다 마음을 조금 가라앉히고 한 문장만 부드럽게 건네보세요.');setText('#a4','“아까는 내 마음이 앞서서 말이 세졌던 것 같아. 네 생각도 천천히 듣고 싶어.”');localStorage.setItem('bumiMindCount',+(localStorage.getItem('bumiMindCount')||0)+1);localStorage.setItem('bumiLastMood',mood);renderPet();setText('#growthText',petState().char+' '+petState().name+' · 오늘도 내 마음을 외면하지 않았어요.');q('#answer')?.classList.add('on')})}
function showSleep(i){const x=sleep[i];qa('.sleep-star').forEach((b,j)=>b.classList.toggle('on',j===i));setText('#sleepDetailAvatar',avatars[i]);setText('#sleepDetailName',x.name);setText('#sleepDetailStatus',x.today>=7?'오늘은 회복이 좋은 밤이었어요':x.today>=6.3?'무난하게 회복한 밤이에요':'오늘은 몸을 조금 더 챙겨주세요');setText('#sdToday',x.today.toFixed(1)+'h');setText('#sdAvg',x.avg.toFixed(1)+'h');setText('#sdBed',x.bed);setText('#sdWake',x.wake);setText('#sleepRecoveryNote','“'+x.note+'”')}
function renderSleep(){if(!q('#sleepDashboard'))return;setText('#cohortAvg',(sleep.reduce((a,b)=>a+b.today,0)/sleep.length).toFixed(1)+'h');setText('#sevenCount',sleep.filter(x=>x.today>=7).length+'명');setText('#rhythmAvg',Math.round(sleep.reduce((a,b)=>a+b.stable,0)/sleep.length)+'%');const pos=[[12,22],[31,13],[52,25],[76,14],[88,34],[17,57],[39,48],[63,61],[83,70],[51,80]],sky=q('#sleepSky');if(sky){sky.innerHTML=sleep.map((x,i)=>`<button class="sleep-star${i===0?' on':''}" data-i="${i}" style="left:${pos[i][0]}%;top:${pos[i][1]}%"><i style="width:${15+Math.max(0,x.today-5)*5}px;height:${15+Math.max(0,x.today-5)*5}px"></i><span>${x.name}</span></button>`).join('');qa('.sleep-star',sky).forEach(b=>b.addEventListener('click',()=>showSleep(+b.dataset.i)))}const cards=q('#sleepMemberCards');if(cards)cards.innerHTML=sleep.map((x,i)=>`<article class="sleep-person"><div class="sleep-person-top"><div class="avatar">${avatars[i]}</div><div><b>${x.name}</b><small>오늘의 회복 기록</small></div></div><div class="sleep-big">${x.today.toFixed(1)}<small> 시간</small></div><div class="sleep-meter"><i style="width:${Math.min(100,x.today/8*100)}%"></i></div><div class="sleep-meta"><div><small>취침</small><b>${x.bed}</b></div><div><small>기상</small><b>${x.wake}</b></div><div><small>주간 평균</small><b>${x.avg.toFixed(1)}h</b></div><div><small>리듬 안정도</small><b>${x.stable}%</b></div></div><span class="sleep-status${x.today<6.2?' warn':''}">${x.today>=7?'푹 쉬었어요 ✦':x.today>=6.3?'괜찮은 흐름':'오늘은 회복 우선'}</span></article>`).join('');const rhythm=q('#rhythmRows');if(rhythm)rhythm.innerHTML=sleep.map(x=>`<div class="rhythm-row"><span>${x.name}</span><div class="rhythm-bar"><i style="width:${x.stable}%"></i></div><b>${x.stable}%</b></div>`).join('');showSleep(0)}
function init(){renderDaily();renderPet();renderHouse();renderMembers();renderMood();renderSleep();bindTabs();bindCore();setInterval(renderDaily,60000);console.info('BumiChal v7 ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();